server:
  port: 8189
  servlet:
    context-path: /test-server

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#  mvc:
#    view:
#      prefix: classpath:/jsp/
#      suffix: .jsp

  flyway:
    locations: classpath:/db/

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: tg5g98h45g98h45g9845hg98hf9834hf9834hjheriheriuher9g8h384y5934yhhtertg